import type { INodeProperties } from 'n8n-workflow';
import { baseURL } from './shared/transport';

const dateOperations = ['isBusinessDay', 'addBusinessDays', 'countBusinessDays'];

export const operations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		options: [
			{
				name: 'Add Business Days',
				value: 'addBusinessDays',
				action: 'Add business days to a date',
				description: 'Add or subtract business days: due dates, delivery and payment terms',
				routing: { request: { method: 'GET', baseURL, url: '/v1/business-days/add' } },
			},
			{
				name: 'Count Business Days',
				value: 'countBusinessDays',
				action: 'Count business days between two dates',
				description: 'Count business days between two dates, with the holidays in the range',
				routing: { request: { method: 'GET', baseURL, url: '/v1/business-days/between' } },
			},
			{
				name: 'Get Countries',
				value: 'getCountries',
				action: 'Get supported countries',
				description:
					'List the supported countries with their regions, languages, holiday types and weekend',
				routing: {
					request: { method: 'GET', baseURL, url: '/v1/holidays/countries' },
					output: {
						postReceive: [{ type: 'rootProperty', properties: { property: 'countries' } }],
					},
				},
			},
			{
				name: 'Get Holidays',
				value: 'getHolidays',
				action: 'Get public holidays',
				description: 'Get the public holidays of a country (and region) for one year',
				routing: {
					request: { method: 'GET', baseURL, url: '/v1/holidays' },
					output: { postReceive: [{ type: 'rootProperty', properties: { property: 'holidays' } }] },
				},
			},
			{
				name: 'Is Business Day',
				value: 'isBusinessDay',
				action: 'Check if a date is a business day',
				description: 'Check whether a date is a business day and, if not, why',
				routing: { request: { method: 'GET', baseURL, url: '/v1/business-days/is' } },
			},
		],
		default: 'getHolidays',
	},
	{
		displayName: 'Country',
		name: 'country',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'DE',
		description: 'Two-letter country code (ISO 3166-1 alpha-2), for example DE, FR, US',
		displayOptions: { show: { operation: ['getHolidays', ...dateOperations] } },
		routing: { send: { type: 'query', property: 'country' } },
	},
	{
		displayName: 'Year',
		name: 'year',
		type: 'number',
		default: 2026,
		required: true,
		typeOptions: { minValue: 1990, maxValue: 2050 },
		displayOptions: { show: { operation: ['getHolidays'] } },
		routing: { send: { type: 'query', property: 'year' } },
	},
	{
		displayName: 'Date',
		name: 'date',
		type: 'string',
		default: '',
		required: true,
		placeholder: '2026-12-24',
		description: 'Date in ISO format (YYYY-MM-DD)',
		displayOptions: { show: { operation: ['isBusinessDay', 'addBusinessDays'] } },
		routing: { send: { type: 'query', property: 'date' } },
	},
	{
		displayName: 'Business Days',
		name: 'days',
		type: 'number',
		default: 10,
		required: true,
		typeOptions: { minValue: -1000, maxValue: 1000 },
		description: 'Business days to add; a negative number goes back in time',
		displayOptions: { show: { operation: ['addBusinessDays'] } },
		routing: { send: { type: 'query', property: 'days' } },
	},
	{
		displayName: 'Start Date',
		name: 'start',
		type: 'string',
		default: '',
		required: true,
		placeholder: '2026-12-01',
		description: 'First day, included (YYYY-MM-DD)',
		displayOptions: { show: { operation: ['countBusinessDays'] } },
		routing: { send: { type: 'query', property: 'start' } },
	},
	{
		displayName: 'End Date',
		name: 'end',
		type: 'string',
		default: '',
		required: true,
		placeholder: '2026-12-31',
		description: 'Last day, included (YYYY-MM-DD)',
		displayOptions: { show: { operation: ['countBusinessDays'] } },
		routing: { send: { type: 'query', property: 'end' } },
	},
	{
		displayName: 'Options',
		name: 'holidayOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { operation: ['getHolidays'] } },
		options: [
			{
				displayName: 'Language',
				name: 'language',
				type: 'string',
				default: '',
				placeholder: 'de',
				description: 'Language of the holiday names, for example en, de, fr',
				routing: { send: { type: 'query', property: 'language' } },
			},
			{
				displayName: 'Region',
				name: 'subdivision',
				type: 'string',
				default: '',
				placeholder: 'BY',
				description: 'State, region or province code (or name), for example BY for Bavaria',
				routing: { send: { type: 'query', property: 'subdivision' } },
			},
			{
				displayName: 'Holiday Types',
				name: 'types',
				type: 'string',
				default: 'public',
				description: 'Comma-separated holiday categories, for example public,bank',
				routing: { send: { type: 'query', property: 'types' } },
			},
		],
	},
	{
		displayName: 'Options',
		name: 'businessDayOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { operation: dateOperations } },
		options: [
			{
				displayName: 'Region',
				name: 'subdivision',
				type: 'string',
				default: '',
				placeholder: 'BY',
				description: 'State, region or province code (or name), for example BY for Bavaria',
				routing: { send: { type: 'query', property: 'subdivision' } },
			},
			{
				displayName: 'Weekend',
				name: 'weekend',
				type: 'string',
				default: '',
				placeholder: 'fri,sat',
				description: "Override the country's weekend days",
				routing: { send: { type: 'query', property: 'weekend' } },
			},
			{
				displayName: 'Extra Closing Days',
				name: 'extra_holidays',
				type: 'string',
				default: '',
				placeholder: '2026-12-24,2026-12-31',
				description: 'Your own closing days, comma-separated ISO dates (up to 100)',
				routing: { send: { type: 'query', property: 'extra_holidays' } },
			},
		],
	},
];
