// Generated by generate.mjs: this package's API on each marketplace.
export const API_TITLE = 'Public Holidays and Business Days';
export const API_MARKET_SLUG = 'public-holidays';
export const RAPIDAPI_HOST = 'public-holidays-and-business-days.p.rapidapi.com';
